"""Constants and mappings - loaded from Vault environment variables"""
import os


# Master component mapping - values loaded from Vault via environment variables
REPO_TO_MASTER_COMPONENT = {
    "dedicated-host": os.getenv("DEH"),
    "auto-scaling": os.getenv("ASG"),
    "elastic-cloud-server": os.getenv("ECS"),
    "image-management-service": os.getenv("IMS"),
    "bare-metal-server": os.getenv("BMS"),
    "relational-database-service": os.getenv("RDS"),
    "gaussdb-opengauss": os.getenv("OPENGAUSS"),
    "geminidb": os.getenv("GEMINIDB"),
    "gaussdb-mysql": os.getenv("MYSQL"),
    "data-replication-service": os.getenv("DRS"),
    "data-admin-service": os.getenv("DAS"),
    "distributed-database-middleware": os.getenv("DDM"),
    "document-database-service": os.getenv("DDS"),
    "marketplace": os.getenv("MKT"),
    "cloud-search-service": os.getenv("CSS"),
    "data-warehouse-service": os.getenv("DWS"),
    "mapreduce-service": os.getenv("MRS"),
    "modelarts": os.getenv("MA"),
    "cloud-eye": os.getenv("CES"),
    "cloud-container-engine": os.getenv("CCE"),
    "cloud-container-instance": os.getenv("CCI"),
    "enterprise-dashboard": os.getenv("ED"),
    "status-dashboard": os.getenv("SD"),
    "direct-connect": os.getenv("DC"),
    "domain-name-service": os.getenv("DNS"),
    "elastic-load-balancing": os.getenv("ELB"),
    "api-gateway": os.getenv("APIG"),
    "application-operations-management": os.getenv("AOM"),
    "application-performance-management": os.getenv("APM"),
    "cloud-trace-service": os.getenv("CTS"),
    "distributed-cache-service": os.getenv("DCS"),
    "function-graph": os.getenv("FGS"),
    "log-tank-service": os.getenv("LTS"),
    "host-security-service": os.getenv("HSS"),
    "identity-access-management": os.getenv("IAM"),
    "key-management-service": os.getenv("KMS"),
    "data-lake-insight": os.getenv("DLI"),
    "data-arts-studio": os.getenv("DAS_STUDIO"),
    "optical-character-recognition": os.getenv("OCR"),
    "cloud-connect": os.getenv("CCN"),
    "elastic-ip": os.getenv("EIP"),
    "enterprise-router": os.getenv("ER"),
    "enterprise-switch": os.getenv("ESW"),
    "nat-gateway": os.getenv("NATGW"),
    "private-link-access-service": os.getenv("PLAS"),
    "virtual-private-cloud": os.getenv("VPC"),
    "vpc-endpoint": os.getenv("VPCEP"),
    "virtual-private-network": os.getenv("VPN"),
    "anti-ddos": os.getenv("ANTIDDOS"),
    "cloud-firewall": os.getenv("CFW"),
    "database-security-service": os.getenv("DBSS"),
    "enterprise-project-service": os.getenv("EPS"),
    "web-application-firewall": os.getenv("WAF"),
    "application-service-mesh": os.getenv("ASM"),
    "software-repository-container": os.getenv("SWR"),
    "distributed-message-service": os.getenv("DMS"),
    "distributed-message-service-rocketmq": os.getenv("DMSROCKETMQ"),
    "cloud-backup-recovery": os.getenv("CBR"),
    "cloud-server-backup-service": os.getenv("CSBS"),
    "elastic-volume-service": os.getenv("EVS"),
    "object-storage-service": os.getenv("OBS"),
    "storage-disaster-recovery-service": os.getenv("SDRS"),
    "scalable-file-service": os.getenv("SFS"),
    "volume-backup-service": os.getenv("VBS"),
    "config": os.getenv("CONFIG"),
    "resource-formation-service": os.getenv("RFS"),
    "simple-message-notification": os.getenv("SMN"),
    "tag-management-service": os.getenv("TMS"),
    "taurusdb": os.getenv("TAURUSDB")
}

# Test category IDS - values loaded from Vault
TEST_CATEGORY_IDS = {
    "QA": os.getenv("QA"),
    "UAT": os.getenv("UAT"),
    "Security": os.getenv("SEC")
}

# Template fields IDs for mapping
template_field_map = {
    "master_component": os.getenv("master_component"),
    "users_impact": os.getenv("users_impact"),
    "affected_locations": os.getenv("affected_locations"),
    "test_category": os.getenv("test_category"),
    "priority": os.getenv("priority"),
    "bug_type": os.getenv("bug_type"),
    "affected_areas": os.getenv("affected_areas"),
    "estimated_effort": os.getenv("estimated_effort"),
    "tier": os.getenv("tier"),
    "pays_into": os.getenv("pays_into"),
    "description": os.getenv("description")
}
